Status effects indicators battle
lambdaclass/afk_gacha_game pull request #367
Opened 2024-04-17 22:22 UTC by tkz00

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-29 19:24 UTC, ncontinanza requested changes
Working great! Just left a comment about a log

2024-04-29 19:24 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +			Debug.Log($"step: {step.StepNumber}");
Do we need this comment? It's making the log huge on the client

2024-04-29 19:32 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +			Debug.Log($"step: {step.StepNumber}");
Sorry, my bad, removed the line!

2024-04-29 19:51 UTC, ncontinanza approved these changes
Nice!

2024-05-02 18:21 UTC, tkz00 commented
> please use a different icon for Defense and Damage Reduction

Fixed!

2024-05-15 20:44 UTC, ncontinanza submitted a review, later dismissed

2024-05-17 19:28 UTC, lotuuu requested changes
Let's change the Paralyze icon since the ❄️ would belong to freeze! You can check possible status effects here: https://docs.google.com/spreadsheets/d/1qLoq8PrQpByb_TaQaxlm8lgQkd1mQSSW4dTxoc7M7fM/edit#gid=666137060

2024-05-17 19:28 UTC, lotuuu commented on client/Assets/Scripts/Battle/BattleManager.cs
> +								Debug.LogError($"status not found on client: {prefix + action.ModifierReceived.StatAffected.Stat.ToString().ToLower()}");
I think logging these as errors is a bit too harsh. We're expecting to get a lot of tags that are more "internal use"-ish and won't receive animations/feedback. We can keep this log but maybe as a warning or even just info. Same for tags.

2024-05-17 21:27 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +								Debug.LogError($"status not found on client: {prefix + action.ModifierReceived.StatAffected.Stat.ToString().ToLower()}");
You're right! Changed

2024-05-17 21:27 UTC, tkz00 commented
> Let's change the Paralyze icon since the ❄️ would belong to freeze! You can check possible status effects here: https://docs.google.com/spreadsheets/d/1qLoq8PrQpByb_TaQaxlm8lgQkd1mQSSW4dTxoc7M7fM/edit#gid=666137060

Changed to a little guy being electrocuted!

2024-05-20 14:24 UTC, ncontinanza submitted a review, later dismissed
LGTM!

2024-05-20 20:59 UTC, ncontinanza approved these changes

2024-05-23 15:19 UTC, lotuuu approved these changes

2024-05-23 16:18 UTC, martinacantaro approved these changes

2024-05-23 16:32 UTC, merged