[GH-435] Supercampaigns scene
lambdaclass/afk_gacha_game pull request #444
Opened 2024-05-09 21:35 UTC by ncontinanza

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-05-14 21:59 UTC, tkz00 requested changes
<img width="250" alt="Screenshot 2024-04-08 at 4 32 47 PM" src="https://github.com/lambdaclass/champions_of_mirra/assets/67983386/f710ee33-afcc-465c-9ea7-1a4db7e65330">

The back button isn't visible in the screen, I couldn't take a full look at why, but I know it works fine in the campaign scene, tomorrow we can check that out and fix this scene.

2024-05-15 21:02 UTC, tkz00 commented on client/Assets/Scripts/CampaignsMap/SupercampaignsMapManager.cs
> +
I think there are better alternatives to using `Resources.Load`, I haven't used them yet, but I think Addressables are a better alternative for what we are trying to achieve here, even if this isn't the answer I would look for other options.

2024-05-15 22:36 UTC, tkz00 reviewed
I think objects that don't vary with the supercampaign, such as the canvas, the header or the back button, shouldn't be inside the supercampaign prefab, mainly for maintenance and organizational reasons.

![image](https://github.com/lambdaclass/champions_of_mirra/assets/67983386/a08bcf19-06e9-4fb3-803a-74ff163a1f60)

2024-05-20 14:51 UTC, tkz00 requested changes
While the Main supercampaign prefab works, the template has some transform properties that need to be changed: the rect transform of the parent object, the Map object and the Campaigns object all should have the same values as the Main prefab.

This causes the new prefab variants for supercampaigns to not display correctly when they should.

2024-05-20 14:58 UTC, tkz00 requested changes
The `Supercampaign` scriptable object is unused and should be removed. Also the ElMessiri font shouldn't be added in this PR.

2024-05-23 20:37 UTC, tkz00 requested changes
<img width="406" alt="Screenshot 2024-05-23 at 5 34 19 PM" src="https://github.com/lambdaclass/afk_gacha_game/assets/67983386/651a6f88-b539-44e6-8cba-6676254563cc">

The images for the victory rewards seem to be broken.

2024-05-23 21:13 UTC, tkz00 approved these changes
Works great!

2024-05-24 14:21 UTC, lotuuu approved these changes

2024-05-24 23:06 UTC, tkz00 approved these changes
I think it would be interesting to be able to dynamically instantiate the required campaign without having to add an if statemenet on `SupercampaignsMapManager.cs` and a method on `AddressableInstantiator.cs` for each supercampaign, but for now I feel its good, and maybe what I said won't ever be necessary.

2024-05-24 23:07 UTC, merged