Previous scene navigation
lambdaclass/afk_gacha_game pull request #445
Opened 2024-05-10 15:26 UTC by tkz00

Closes #434 

## Motivation

Currently, the back button relies on a pre-defined scene name to transition, which becomes problematic when the same scene (like the campaignsMap) can be reached from multiple places (Overworld and Dungeon in this case).  For the upcoming dungeon feature, the back button should return the user to the scene they came from, not a fixed scene.  A hardcoded value won't work in this scenario.

## Summary of changes

- New logic for scene navigation has been added, now a stack of the visited scenes is maintained through the lifetime of the application, when a back button is pressed, the scene with the name on top of this stack is loaded, and the name removed from the stack.
- `LevelManager` script has been renamed to `SceneNavigator`, which is a much better fitting name, even more now since it holds the logic of changing scenes, including the back buttons functionality.

## How has this been tested?

Navigate through all the scenes and test the back button on each one is taking you to the previous scene. (Be aware [the Inventory screen is broken](https://github.com/lambdaclass/champions_of_mirra/issues/446))

2024-05-14 19:39 UTC, ncontinanza requested changes

2024-05-14 19:39 UTC, ncontinanza commented on client/Assets/Scripts/CampaignsMap/CampaignItem.cs
> +            // sceneNavigator.ChangeToSceneWithDelay("Campaign");
```suggestion
```

2024-05-14 19:46 UTC, ncontinanza approved these changes

2024-05-15 20:50 UTC, ncontinanza approved these changes

2024-05-16 20:08 UTC, lotuuu requested changes

2024-05-16 20:08 UTC, lotuuu commented on client/Assets/Scripts/Shared/SceneNavigator.cs
> +using System.Collections;
This file is not formatted! Saving any changes here formats the file entirely for me (with the setting    `"editor.formatOnSave": true` in vscode). Does it format it differently for you or did you have this setting off?

2024-05-20 21:04 UTC, ncontinanza approved these changes
LGTM!

2024-05-23 15:30 UTC, lotuuu approved these changes
Approving since format issues will be ignored until #456

2024-05-23 15:30 UTC, merged