Dungeon Settlement Scene
lambdaclass/afk_gacha_game pull request #451
Opened 2024-05-13 21:01 UTC by tkz00

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-05-20 14:31 UTC, ncontinanza requested changes

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/Campaign/CampaignLevelIndicator.cs
Watch out for formatting here!

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/Campaign/CampaignLevelsManager.cs
Watch out for formatting here!

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/Campaign/CampaignManager.cs
Watch out for formatting here!

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/CampaignsMap/CampaignItem.cs
Watch out for formatting here!

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/CampaignsMap/CampaignsMapManager.cs
Watch out for formatting here!

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/KalineTreeManager.cs
Watch out for formatting here!

2024-05-20 14:31 UTC, ncontinanza commented on client/Assets/Scripts/UnitList/UnitListManager.cs
Watch out for formatting here!

2024-05-23 16:35 UTC, tkz00 commented on client/Assets/Scripts/Dungeon/DungeonSettlementManager.cs
Nice catch, removed!

2024-05-23 17:29 UTC, ncontinanza approved these changes
LGTM!

2024-05-23 18:47 UTC, lotuuu requested changes
The inventory button is still there in the Dungeon scene but doesn't do anything! I say we just delete it

2024-05-23 19:57 UTC, tkz00 commented
> The inventory button is still there in the Dungeon scene but doesn't do anything! I say we just delete it

Right! Removed the button!

2024-05-23 20:25 UTC, lotuuu approved these changes

2024-05-23 20:32 UTC, ncontinanza requested changes

2024-05-23 20:32 UTC, ncontinanza commented on client/Assets/Scenes/DungeonSettlement.unity
Notice that in this scene there are two currency sprites overlapping:

![image](https://github.com/lambdaclass/afk_gacha_game/assets/17294394/1109223d-bdd1-4e63-9e8d-ddbf7435706a)

2024-05-23 20:41 UTC, tkz00 commented on client/Assets/Scenes/DungeonSettlement.unity
Bullseye! It's fixed

2024-05-23 20:51 UTC, ncontinanza approved these changes

2024-05-23 21:13 UTC, lotuuu approved these changes

2024-05-23 21:13 UTC, merged