Display afk rewards dynamically
lambdaclass/afk_gacha_game pull request #460
Opened 2024-05-16 20:48 UTC by tkz00

Closes #362

## Motivation

When claiming afk rewards the currencies available are variable, some currencies will have 0 generation rate and we were showing them in the popup, this shouldn't happen.

## Summary of changes

Created an afk reward detail prefab and instantiated it in the popup to show which currencies are up for claim.

## How has this been tested?

Change which currencies your user idly generates, either via normal or artificial means, such as modifying the database or the backend directly, check the claim afk rewards claim popup in the Kaline tree reflects this by showing those currencies.

2024-05-20 14:48 UTC, ncontinanza requested changes

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/AfkRewards/AfkReward.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/AfkRewards/AfkRewardRate.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/Campaign/LevelData.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/Shared/GlobalUserData.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/Shared/HeaderManager.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/Shared/UIReward.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/Summon/Box.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/UnitDetail/UIEquipmentListElement.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/UnitDetail/UnitDetail.cs
Watch out for formatting here!

2024-05-20 14:48 UTC, ncontinanza commented on client/Assets/Scripts/User/User.cs
Watch out for formatting here!

2024-05-23 18:51 UTC, ncontinanza approved these changes
LGTM!

2024-05-23 20:18 UTC, lotuuu approved these changes
Works great! Doesn't even break if there are no rates available! Nice one

2024-05-23 20:18 UTC, merged