[GH-456] CI/CD for formatting check
lambdaclass/afk_gacha_game pull request #461
Opened 2024-05-17 15:43 UTC by ncontinanza

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-05-20 14:07 UTC, tkz00 commented on Makefile
> +.PHONY: generate-protos setup
```suggestion
.PHONY: generate-protos setup format
```

The `format` command must be added as phony to be accessible from the terminal.

2024-05-20 15:06 UTC, tkz00 approved these changes
Great work!

2024-05-28 14:50 UTC, tkz00 submitted a review, later dismissed

2024-05-29 19:36 UTC, lotuuu requested changes

2024-05-29 19:36 UTC, lotuuu commented on README.md
> +- Add dotnet-format to your PATH running the following command in your terminal:
```suggestion
- Add dotnet-format to your PATH by running the following command in your terminal:
```

2024-05-29 19:37 UTC, lotuuu approved these changes

2024-05-29 21:36 UTC, merged