[GH-438] Implement dungeon settlement level up. Fix currency assets
lambdaclass/afk_gacha_game pull request #472
Opened 2024-05-27 18:00 UTC by ncontinanza

Closes #438 

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-05-28 17:16 UTC, lotuuu submitted a review, later dismissed

2024-06-04 20:47 UTC, tkz00 commented on client/Assets/Scripts/BackendConnection/SocketConnection.cs
> +using UnityEngine.Analytics;
```suggestion
```

2024-06-04 20:47 UTC, tkz00 submitted a review, later dismissed
Looks good! Just check the suggestion I left!

2024-06-04 21:02 UTC, tkz00 requested changes
<img src="https://github.com/lambdaclass/afk_gacha_game/assets/67983386/c06ea8c1-9235-480c-a3fd-1d45d9d063ae" width="200">


Shouldn't the afk rate appear also on the popup? Between the parentheses?

Don't mind the broken assets, I haven't downloaded them.

2024-06-04 21:07 UTC, ncontinanza commented
> Shouldn't the afk rate appear also on the popup? Between the parentheses?

Yeah, I'll tackle that pop up when I implement the rewards claim

2024-06-04 21:16 UTC, tkz00 commented
> > Shouldn't the afk rate appear also on the popup? Between the parentheses?
> 
> Yeah, I'll tackle that pop up when I implement the rewards claim

Great! Then You have my approve!

2024-06-04 21:16 UTC, tkz00 submitted a review, later dismissed

2024-06-05 14:17 UTC, lotuuu requested changes
I modified the seeds to make the las dungeon settlement level have no level_up_cost (something likely to happen when we have real data) and the app crashed:

```
Sequence contains no matching element
UnityEngine.Debug:LogError (object)
SocketConnection:AwaitLevelUpDungeonSettlementResponse (byte[],System.Action`1<User>,System.Action`1<string>) (at Assets/Scripts/BackendConnection/SocketConnection.cs:984)
SocketConnection/<>c__DisplayClass52_0:<LevelUpDungeonSettlement>b__0 (byte[]) (at Assets/Scripts/BackendConnection/SocketConnection.cs:958)
NativeWebSocket.WebSocket:DispatchMessageQueue () (at Assets/WebSocket/WebSocket.cs:640)
SocketConnection:Update () (at Assets/Scripts/BackendConnection/SocketConnection.cs:44)
```
Seeds modification: 
Line 297
```
            level_up_costs:
              case level_number do
                20 ->
                  []

                level_number ->
                  [
                    %{currency_id: gold_currency.id, amount: level_number * 100},
                    %{currency_id: blueprints_currency.id, amount: level_number * 50}
                  ]
              end,
```

2024-06-06 14:44 UTC, merged