Rename rate to daily_rate
lambdaclass/afk_gacha_game pull request #480
Opened 2024-06-05 21:02 UTC by lotuuu

To be merged with https://github.com/lambdaclass/mirra_backend/pull/668

## Motivation

Updates protobuf messages to sync them with the backend PR

## Summary of changes

Rename protobuf message, inner class and all occurrences of rate to daily_rate

## How has this been tested?

Go through a basic game loop through the client.

2024-06-07 14:01 UTC, tkz00 requested changes

2024-06-07 15:47 UTC, tkz00 requested changes

2024-06-07 15:47 UTC, tkz00 commented on client/Assets/Scripts/AfkRewards/KalineTreeManager.cs
> +                afkRewardDetail.SetData(GlobalUserData.Instance.AvailableCurrencies.Single(currency => currency.name == afkReward.currency).image, $"{afkReward.amount} ({user.User.kalineTreeLevel.afk
![image](https://github.com/lambdaclass/afk_gacha_game/assets/67983386/e24944be-c542-4ddc-ab87-533b74a9afcd)

I think the calculation in this line is outdated, since we are displaying the afk rate by the minute in the popup, shouldn't it be the `daily_rate / (hours_in_a_day * minutes_in_an_hour)`?

2024-06-10 13:18 UTC, tkz00 approved these changes

2024-06-10 13:19 UTC, tkz00 commented on client/Assets/Scripts/AfkRewards/KalineTreeManager.cs
> +                afkRewardDetail.SetData(GlobalUserData.Instance.AvailableCurrencies.Single(currency => currency.name == afkReward.currency).image, $"{afkReward.amount} ({user.User.kalineTreeLevel.afk
This was fixed!

2024-06-10 15:21 UTC, ncontinanza approved these changes
LGTM!

2024-06-10 15:21 UTC, merged